apiVersion: v1
kind: Secret
metadata:
  name: appwrite-emqx-authentication
  namespace: appwrite
type: Opaque
stringData:
  authentication: |-
    [{
      mechanism = password_based
      backend = http
      method = post
      url = "http://appwrite/v1/devices/sessions"
      headers {
        "content-type" = "application/json"
        "x-appwrite-project" = "console"
        "x-appwrite-emqx-secret" = "REPLACE_WITH_THE_APPWRITE_EMQX_SECRET"
      }
      body {
        username = "${username}"
        password = "${password}"
        clientid = "${clientid}"
      }
      connect_timeout = "5s"
      request_timeout = "5s"
      pool_size = 16
      enable_pipelining = 100
    }]
